version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_apache
    depends_on:
      - db
    volumes:
      - ./camagru-dev:/var/www/html/
    ports:
      - 8000:80
      - 4430:443
  db:
    container_name: mysqldb
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abenani
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: abenani
volumes:
  db_data: